apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: grocery
spec:
  replicas: 1
  selector:
    matchLabels: {app: order-service}
  template:
    metadata:
      labels: {app: order-service}
    spec:
      containers:
        - name: app
          image: your-acr.azurecr.io/order-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/order_db
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef: {name: grocery-secrets, key: SPRING_DATASOURCE_USERNAME}
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef: {name: grocery-secrets, key: SPRING_DATASOURCE_PASSWORD}            - name: INVENTORY_BASE_URL
              value: http://inventory-service:8083
            - name: PAYMENT_BASE_URL
              value: http://payment-service:8086
          readinessProbe:
            httpGet: {path: /actuator/health, port: 8085}
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet: {path: /actuator/health, port: 8085}
            initialDelaySeconds: 40
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: grocery
spec:
  selector: {app: order-service}
  ports:
    - port: 8085
      targetPort: 8085
