apiVersion: v1
kind: Namespace
metadata:
  name: grocery
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grocery-config
  namespace: grocery
data:
  AUTH_MODE: "DEV"
  APP_CORS_ALLOWED_ORIGINS: "http://localhost:4200"
---
apiVersion: v1
kind: Secret
metadata:
  name: grocery-secrets
  namespace: grocery
type: Opaque
stringData:
  JWT_SECRET: "replace-with-strong-key"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
